package org.processmining.placebasedlpmdiscovery.view.components.configurationcomponents.configurations.lpmsimilarity;

import org.processmining.placebasedlpmdiscovery.view.components.configurationcomponents.configurations.ViewConfiguration;

public interface LPMSimilarityViewConfiguration extends ViewConfiguration {

}
